stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: openjdk:11
  tags:
    - yigwak2
  before_script:
    - mkdir src/main/resources
    - touch src/main/resources/application.yml
    - touch src/main/resources/application-test.yml
    - echo "$APPLICATION_INFO" > "src/main/resources/application.yml"
    - echo "$APPLICATION_TEST_INFO" > "src/main/resources/application-test.yml"
  script:
    - id
    - whoami
    - ./gradlew clean
    - ./gradlew build
  artifacts:
      paths:
          - build/libs/*.jar
      expire_in: 60 min