stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: openjdk:17-oracle
  tags:
    - yigwak2
  before_script:
    - microdnf install findutils
    - echo pwd
    - cd src/main
    - mkdir resources
    - echo "$APPLICATION_INFO" > "/src/main/resources/application.yml"
  script:
    - id
    - whoami
    - ./gradlew clean
    - ./gradlew build
  artifacts:
      paths:
          - build/libs/*.jar
      expire_in: 60 min